CREATE TABLE AUTH_TOKEN (
    TOKEN_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,

    TOKEN VARCHAR2(255) NOT NULL,
    TOKEN_TYPE VARCHAR2(30) NOT NULL,

    EXPIRY_TIME TIMESTAMP NOT NULL,
    USED CHAR(1) DEFAULT 'N',

    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_TOKEN_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
);