CREATE TABLE LOGIN_ATTEMPT (
    ATTEMPT_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER,

    ATTEMPT_TIME TIMESTAMP,
    SUCCESS CHAR(1),

    IP_ADDRESS VARCHAR2(50),

    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_LOGIN_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
);