CREATE TABLE USER_ROLE (
    USER_ID NUMBER NOT NULL,
    ROLE_ID NUMBER NOT NULL,

    CONSTRAINT PK_USER_ROLE PRIMARY KEY (USER_ID, ROLE_ID),

    CONSTRAINT FK_UR_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT FK_UR_ROLE FOREIGN KEY (ROLE_ID)
        REFERENCES ROLES(ROLE_ID)
);