CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(150) NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,

    STATUS VARCHAR2(20) NOT NULL,
    FAILED_ATTEMPTS NUMBER DEFAULT 0,
    LOCKED_UNTIL TIMESTAMP NULL,

    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NULL
);






ALTER TABLE USERS ADD CONSTRAINT UK_USERNAME UNIQUE (USERNAME);
ALTER TABLE USERS ADD CONSTRAINT UK_EMAIL UNIQUE (EMAIL);